# Generated by Django 5.0.3 on 2024-03-18 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(blank=True, max_length=255)),
                ('connect', models.TextField(blank=True)),
                ('add_time', models.DateTimeField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_fam', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_otc', models.CharField(max_length=255)),
                ('coords_latitude', models.FloatField()),
                ('coords_longitude', models.FloatField()),
                ('coords_height', models.IntegerField()),
                ('level_winter', models.CharField(blank=True, max_length=255)),
                ('level_summer', models.CharField(blank=True, max_length=255)),
                ('level_autumn', models.CharField(blank=True, max_length=255)),
                ('level_spring', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pereval_images/')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restapi.pereval')),
            ],
        ),
    ]
